name: Test

# Controls when the action will run. 
on:
  pull_request:
    types: [opened, synchronize, closed] 

# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
   
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
#     if: |
#       ${{ github.event_name == 'pull_request' || ( github.event.action == 'opened' || github.event.action == 'synchronize' ) }}
    steps:
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: |
          echo "Hello World!!!"
          echo ${{ github.event_name }} 
          echo ${{ github.event.pull_request.merged }}
          echo ${{ github.event.action }}
          
          echo ${GITHUB_HEAD_REF}
          echo ${GITHUB_REF}
          
          if [[ $GITHUB_REF == *"refs/pull/"* ]]; then
            PACKAGE_VERSION="${PACKAGE_VERSION}-SNAPSHOT-feature-${GITHUB_HEAD_REF##*/}-${VERSION_DATE}"
            echo $PACKAGE_VERSION
          fi
